[package]
name = "ddwill"
version = "0.2.1"
edition = "2021"
description = "Your digital distributed will."
readme = "README.md"
repository = "https://bitbucket.org/axonibyte/ddwill"
license = "Apache-2.0"
rust-version = "1.85"

[dependencies]
aes-gcm-siv = "0.12.1"
argon2 = { version = "0.6.0", default-features = false, features = ["alloc"] }
bincode = { version = "2.0.1", default-features = false, features = ["std", "serde"] }
clap = { version = "4.6", features = ["cargo", "derive"] }
crypto-common = "0.2.2"
env_logger = "0.11.11"
getrandom = "0.4"
itertools = "0.15.0"
log = "0.4.34"
serde = { version = "1.0.229", features = ["derive"] }

[dev-dependencies]
tempfile = "3"
